# permissions for end users to edit dravens.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: draven-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubebuilder-test
    app.kubernetes.io/part-of: kubebuilder-test
    app.kubernetes.io/managed-by: kustomize
  name: draven-editor-role
rules:
- apiGroups:
  - batch.my.domain
  resources:
  - dravens
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.my.domain
  resources:
  - dravens/status
  verbs:
  - get
